---
# tasks file for start-http-server

- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Upload nginx conf on server
  ansible.builtin.copy:
    src: '{{ role_path }}/files/demo-site.nginx'
    dest: /etc/nginx/sites-available/demo-site.nginx

- name: Enable site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/demo-site.nginx
    dest: /etc/nginx/sites-enabled/00_demo-site.nginx
    state: link

- name: Remove default conf
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: start http service
  ansible.builtin.systemd:
    name: nginx.service
    daemon_reload: yes
    state: restarted